
//////////////////////////////////////////////////////////////
//
// Header file for MainFormUI
//
//    This file is generated by RapidApp 1.2
//
//    This class implements the user interface portion of a class
//    Normally it is not used directly.
//    Instead the subclass, MainForm is instantiated
//
//    To extend or alter the behavior of this class, you should
//    modify the MainForm files
//
//    Restrict changes to those sections between
//    the "//--- Start/End editable code block" markers
//
//    This will allow RapidApp to integrate changes more easily
//
//    This class is a ViewKit user interface "component".
//    For more information on how components are used, see the
//    "ViewKit Programmers' Manual", and the RapidApp
//    User's Guide.
//
//////////////////////////////////////////////////////////////
#ifndef MAINFORMUI_H
#define MAINFORMUI_H
#include <Vk/VkComponent.h>


//---- Start editable code block: headers and declarations


//---- End editable code block: headers and declarations


class MainFormUI : public VkComponent
{ 

  public:

    MainFormUI(const char *, Widget);
    MainFormUI(const char *);
    ~MainFormUI();
    void create ( Widget );
    const char *  className();

    //---- Start editable code block: MainForm public


    //---- End editable code block: MainForm public


  protected:


    // Widgets created by this class

    Widget  _alphaGLFrame;
    Widget  _alpha_GLWidget;
    Widget  _customizeButton;
    Widget  _destAlphaLabel;
    Widget  _effectsForm;
    Widget  _effectsScrolledWindow;
    Widget  _frameSlider;
    Widget  _label1;
    Widget  _label2;
    Widget  _mainForm;
    Widget  _radiobox;
    Widget  _resultGLFrame1;
    Widget  _result_GLWidget;
    Widget  _scrolledList;
    Widget  _sourceAButton;
    Widget  _sourceA_GLWidget;
    Widget  _sourceBButton;
    Widget  _sourceB_GLWidget;
    Widget  _srcAGLFrame;
    Widget  _srcBGLFrame;
    Widget  _toggle1;
    Widget  _toggle2;


    // These virtual functions are called from the private callbacks (below)
    // Intended to be overriden in derived classes to define actions

    virtual void doFilters ( Widget, XtPointer );
    virtual void doFrameSlider ( Widget, XtPointer );
    virtual void doSetup ( Widget, XtPointer );
    virtual void doTransitions ( Widget, XtPointer );

    virtual void glInput ( Widget, XtPointer );
    virtual void loadSourceA ( Widget, XtPointer );
    virtual void loadSourceB ( Widget, XtPointer );

    //---- Start editable code block: MainForm protected


    //---- End editable code block: MainForm protected


  private: 
    // Array of default resources

    static String      _defaultMainFormUIResources[];

    // Callbacks to interface with Motif

    static void doFiltersCallback ( Widget, XtPointer, XtPointer );
    static void doFrameSliderCallback ( Widget, XtPointer, XtPointer );
    static void doSetupCallback ( Widget, XtPointer, XtPointer );
    static void doTransitionsCallback ( Widget, XtPointer, XtPointer );
    static void glInputCallback ( Widget, XtPointer, XtPointer );
    static void loadSourceACallback ( Widget, XtPointer, XtPointer );
    static void loadSourceBCallback ( Widget, XtPointer, XtPointer );

    //---- Start editable code block: MainForm private


    //---- End editable code block: MainForm private
};
//---- Start editable code block: End of generated code


//---- End editable code block: End of generated code

#endif

