#!smake
# $Revision: 1.2 $

include $(ROOT)/usr/include/make/commondefs

LLDLIBS = -lvl -limage -lX11 -lGL -ldmedia

LCOPTS = -prototypes

OPTIMIZER = -O

TARGETS = vtom mtov vtov vtos

default: $(TARGETS)

include $(COMMONRULES)
