#!smake
# Copyright 1998 Silicon Graphics, Inc.  All rights reserved.
#

# $Revision: 1.00

include commondefs

LLDLIBS= -lc -lavc

OPTIMIZER= -g

TARGETS =       \
		allocchannel 		\
		allocbandwidth 		\
		command 		\
		displaytree 		\
		displayunit 		\
		freebandwidth 		\
		freechannel 		\
		getunitchannels 	\
	 	openbus 		\
		printtimecode 		\
		recvframe 		\
		searchtimecode 		\
		selectbusreset 		\
		sendframe 		\
		setoutputchannel 	\
		$(NULL) 

#
# Rules
#

default:        $(TARGETS)

include commonrules
