#! smake
# 
# $Revision: 1.18 $

include $(ROOT)/usr/include/make/commondefs

SUBDIRS = common \
	  addaudio \
	  createmovie \
	  editmovie \
          manymovie \
          manymovieGL \
          misc \
          motifmovie \
          miscGL \
          sceneDetector \
          snapmovie \
          $(NULL)

default:
	$(SUBDIRS_MAKERULE)

clean:
	$(SUBDIRS_MAKERULE)

clobber:
	$(SUBDIRS_MAKERULE)
